services:
  api:
    platform: linux/amd64
    build:
      context: ./backend

    env_file:
      - ./backend/.env
      
    ports:
      - "4003:8000"

    volumes:
      - ./backend:/app
      - ./backend/static:/app/static

    command: gunicorn task_manager.wsgi:application --bind 0.0.0.0:8000