services:

  api:
    image: ghcr.io/kevindebenedetti/team_todolist-api:latest
    pull_policy: always
    restart: always
    expose:
      - 8000
    command: >
      sh -c "python manage.py collectstatic --noinput && 
        gunicorn task_manager.wsgi:application --bind 0.0.0.0:8000"
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      CSRF_TRUSTED_ORIGINS: ${CSRF_TRUSTED_ORIGINS}
      DEFAULT_API_URL: ${DEFAULT_API_URL}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.api-app.rule=Host(`todolist.kevindb.dev`)
      - traefik.http.routers.api-app.entrypoints=web
      - traefik.http.services.api-app.loadbalancer.server.port=8000

networks:
  dokploy-network:
    external: true